### ISSUE TITLE
duplicated icons in status bar

### ISSUE THREAD

**Issue by Jonathan34** [Microsoft/vsts-vscode#141]
I am not sure what triggers this but i keep geeting duplicated icons in the status bar.
i am signed in and everything else appears to work ok. a restart fixes it until it comes back.

vscode 1.11.0-insider (1.11.0-insider) on macOS 10.12.3.
using vsts 1.113.0 extension.

![image](https://cloud.githubusercontent.com/assets/3976137/23712061/4dd2247e-03e7-11e7-885f-d287a176b60c.png)

**Comment by jeffyoung** [comment]
Hi @Jonathan34.  This is something that was reported a while back and was recently fixed (although we haven't yet pushed a new version of the extension yet).  This was #63.  Essentially, changes to either the VS Code configuration (say, CTRL+ or CTRL-) or changes to your git config (which we also listen to) can cause this.  I hope to have a new version of the extension out with the fix fairly soon.

**Comment by Jonathan34** [comment]
@jeffyoung thanks for the answer. i looked at the opened issue for a duplicate but did not check the closed one :) my bad!

**Comment by jeffyoung** [comment]
No problem @Jonathan34.  I just published an update that has the fix for this issue (1.115.0).  Thanks for contributing!

**Comment by Jonathan34** [comment]
This issue is back in Version 1.12.0-insider (1.12.0-insider) (2017-05-03T14:37:53.948Z) and plugin version 1.117.1
![image](https://cloud.githubusercontent.com/assets/3976137/25722149/a93c0c80-30d8-11e7-8b6b-2c925798348d.png)

**Comment by jeffyoung** [comment]
Thanks for the heads-up @Jonathan34.  It looks like CTRL+ and CTRL- do the same in 1.11.x as well (I must have regressed something along the way).

**Comment by Jonathan34** [comment]
no problem, just noticed that changing the theme generates this issue too (this is how i got it initially)

**Comment by jeffyoung** [comment]
Fixed (again!) in v1.117.3.
