### ISSUE TITLE
team.Reinitialize not found

### ISSUE THREAD

**Issue by cameronmolyneux** [Microsoft/vsts-vscode#209]
Just installed TFS2015.3 on premise and trying to connect vscode up to it

The team icon at the bottom displays a tooltip of socket hang up and if I click it I get team.Reinitliaze not found

Any suggestions

thanks

**Comment by jeffyoung** [comment]
Thanks for using the extension @cameronmolyneux.  I submitted a PR for this yesterday (#206) and the update should be out soon.  In the meantime, you'd need to re-open the folder you already have open in VS Code to re-initialize (e.g., close the folder, then re-open the same folder).

**Comment by jeffyoung** [comment]
This should be fixed with 1.117.2 (just released).

**Comment by tegaaa** [comment]
I have the latest code 1.12.1 and version 1.117.3 and I'm still getting the error can't reinitialize and I can't call signin, signout, etc. either.
